version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: s3local
    ports:
      - 4571:4571
      - 4566:4566
      - 8082:8080
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock